### ISSUE TITLE
String manipulation methods

### ISSUE THREAD

**Issue by kingsumos** [ipxe/ipxe#1061]
Hi,

Looks like we don't have any possibility for string manipulation inside iPXE scripts. I found this pull request which was rejected for some reason:
https://github.com/ipxe/ipxe/pull/95
The proposal above will be very helpful, e.g.:
show smbios/product:string:0:8
show smbios/uuid::0:24
echo ${ifname::3:4}

Other user looking for this feature:
https://forum.ipxe.org/showthread.php?tid=18573&pid=36076
(tried adding a post in forum 1st, but new users aren't allowed for registration)

Another string manipulation attempts:
https://forum.ipxe.org/showthread.php?tid=7979
https://forum.ipxe.org/showthread.php?tid=18573
https://forum.ipxe.org/showthread.php?tid=18559

**Comment by kingsumos** [comment]
It would be nice if iPXE can mimic bash-scripting parameter substitution functionality, reference link:
https://tldp.org/LDP/abs/html/parameter-substitution.html

**Comment by NiKiZe** [comment]
String manipulations will not be added to iPXE, even if there is good usecases you are almost always better of sending strings to a server and let more competent languages handle these things.

**Comment by kingsumos** [comment]
Ok no problem Mr. Lennart Poettering
I'm indeed very competent, good luck with your project

**Comment by NiKiZe** [comment]
Better description then mine https://github.com/ipxe/ipxe/discussions/326#discussioncomment-629914
