### ISSUE TITLE
1.21.1 build error

### ISSUE THREAD

**Issue by Zeno-sole** [ipxe/ipxe#1092]
[  155s] core/archive.c:50:44: error: 'struct image_type' has no member named 'extract'
[  155s]    50 |         if ( ! ( image->type && image->type->extract ) ) {

**Comment by NiKiZe** [comment]
Just posting a compile error without any context is unlikely to get any fix.
At least provide a minimal reproducible example, build commandline and compiler version as a minimal.

See https://github.com/ipxe/ipxe/actions/runs/7103251028/job/19335538559 for proof that current git master compiles just fine.

**Comment by Zeno-sole** [comment]
[log-amd64.txt](https://github.com/ipxe/ipxe/files/13578498/log-amd64.txt)
