### ISSUE TITLE
Building latest ipxe efi 

### ISSUE THREAD

**Issue by camachoh** [ipxe/ipxe#1093]
Hello 

I am trying to build the latest and running into this issue. Thanks

```
[HOSTCC] util/elf2efi64
util/elf2efi.c: In function ‘read_elf_file’:
util/elf2efi.c:443:38: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       ( ( elf->len - ehdr->e_phoff ) < ( ehdr->e_phnum *
                                      ^
util/elf2efi.c: At top level:
cc1: error: unrecognized command line option "-Wno-dangling-pointer" [-Werror]
cc1: all warnings being treated as errors
make: *** [util/elf2efi64] Error 1
```

**Comment by krishneel94** [comment]
> gcc --version gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
> 
> Master branch is what i am trying to build. apologies for the lack of info

I had this issue as well. I was trying to build on CentOS 7 which doesn't support the latest versions of GCC. 

I downloaded CentOS Stream 9 to a VM and the build ran with no issues. gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)

**Comment by NiKiZe** [comment]
2015, that is 8 years ;)
iPXE does try to stay compatible, but there is limits, if you still need to build on old gcc, do use git bisect to find latest working version for you.
Or use a more recent host, or docker container.
