### ISSUE TITLE
Windows11 to use iPXE have a error

### ISSUE THREAD

**Issue by lx775289883** [ipxe/ipxe#1122]
I try to use iPXE install Windows11,there is a error!

![Screenshot_20240112_103136_com android gallery3d](https://github.com/ipxe/ipxe/assets/46526084/ea9601fd-53bf-46f0-a1dc-907f1fb6adfd)

https://github.com/ipxe/ipxe/assets/46526084/ffcd650d-6b1d-49ca-9be7-5363a43aa319

**Comment by mcb30** [comment]
It looks as though you have forgotten to load the `wimboot` binary.  See https://ipxe.org/wimboot
