### ISSUE TITLE
Invalid file name when use .. (double dots) in path to store file for wimboot

### ISSUE THREAD

**Issue by ixeldino** [ipxe/ipxe#1127]
I wont store file named 'use.bat" to root of X: drive instead of x:\windows\system32. When i try config:
```
kernel wimboot
initrd use.bat ..\..\use.bat
...some other initrd commands...
boot
```

I not found file on the root of drive but file stored on x:\windows\system32 named "..\..\use.bat".

Screenshot above
![VirtualBox_w10_17_01_2024_15_03_49](https://github.com/ipxe/ipxe/assets/10027564/c6eb63e0-baee-4049-9b78-9ef07ef3f517)

**Comment by NiKiZe** [comment]
This is iPXE repo, not wimboot.
But even so what you ask is not supported, do not use invalid chars in filenames. 

If you have other questions, use discussions, not issues.
