### ISSUE TITLE
Feature Request : Console Position (X - Y) for ECHO (and other text output) also a font size setting

### ISSUE THREAD

**Issue by GRIFFCOMMca** [ipxe/ipxe#1137]
Hi, it would be nice to be able to Echo out some details in a special location on the screen, also the ability to make the font larger for alerts out output.

I cant seem to find anything for this in any documentation.

Many Thanks

**Comment by GRIFFCOMMca** [comment]
Found it in the Wiki (not sure why i didnt see it sooner)

**Comment by mcb30** [comment]
For anyone else wanting the same: iPXE generally supports the use of ANSI escape sequences to control things like cursor placement, colour selection, etc.
