### ISSUE TITLE
qemu + ipv6 promblem

### ISSUE THREAD

**Issue by mcb30** [ipxe/ipxe#1192]
### Discussed in https://github.com/ipxe/ipxe/discussions/1191

<div type='discussions-op-text'>

<sup>Originally posted by **sprootik** April 10, 2024</sup>
Hello.
I made ipxe with ipv6 support and debugging. For the test, I try to run on qemu  (UEFI) and get an error. 
It seems to me that during normal operation the ipxe should load and receive an IP address
![ipxe_problem](https://github.com/ipxe/ipxe/assets/38777214/244b6935-b649-456a-bcf8-b7734e0a12df)

dump in attach
[dump.tar.gz](https://github.com/ipxe/ipxe/files/14927020/dump.tar.gz)
</div>

**Comment by mcb30** [comment]
I have been able to reproduce this locally, and am investigating now.

**Comment by mcb30** [comment]
I am able to reproduce the failure by using the UEFI shell `disconnect` command to attempt to disconnect drivers from the PCI device's handle.  This freezes in the same way as iPXE is freezing (which is on the call to `DisconnectController()`).

**Comment by sprootik** [comment]
Hello.
I checked, now there is no error, but it also freezes during initialization.
Is there any additional information needed from me?

**Comment by mcb30** [comment]
> Hello. I checked and now there is no error message. But IPXE still freezes when initializing devices.

Yes, this is expected.  The error message and the freeze are unrelated.

> Is there any additional information needed from me?

If you are aware of an older commit that used to work, that would be useful.  Otherwise, no.

**Comment by sprootik** [comment]
Alas, I have never used IPv6 before

**Comment by mcb30** [comment]
> I am able to reproduce the failure by using the UEFI shell `disconnect` command to attempt to disconnect drivers from the PCI device's handle. This freezes in the same way as iPXE is freezing (which is on the call to `DisconnectController()`).

I have reproduced very similar symptoms using qemu with the VirtioNetDxe driver and the UEFI shell (ie without any iPXE code), which indicates that (as expected) it is a bug in the EDK2 IPv6 stack.  Still debugging...

**Comment by mcb30** [comment]
OK, after adding many debug messages to the EDK2 codebase I have found the root cause.

When disconnecting the UEFI network stack from the underlying PCI device, the Dhcp6Dxe driver will end up looping indefinitely until it either receives a response packet or a timer tick occurs, either of which will update its `UdpSts` field:
https://github.com/tianocore/edk2/blob/b6cd5ddce9ade43e4215836f12b43ebbb90eecf2/NetworkPkg/Dhcp6Dxe/Dhcp6Impl.c#L224-L234

This is completely broken.  The UEFI specification (version 2.10) states in section 7.1 that "Protocol Handler Services" may be called at any TPL up to and including TPL_NOTIFY.  Assuming that "Protocol Handler Services" means the Protocol Handler Services covered by section 7.3, then this includes `UninstallMultipleProtocolInterfaces()`.  Since uninstalling a protocol may result in a call to `DisconnectController()` to disconnect drivers using the about-to-be-uninstalled protocol, this means that driver stop methods may be called at any TPL up to and including TPL_NOTIFY.

`EfiDhcp6Stop()` may therefore not rely on a timer at TPL_CALLBACK, since that timer may not be firing at the current TPL.

The whole model of TPLs within UEFI is deeply broken, as is the model for uninstallation of protocols.  We've had a few previous commits that work around problems caused by these design and implementation flaws, e.g. https://github.com/ipxe/ipxe/commit/1295b4acf and https://github.com/ipxe/ipxe/commit/25a3d3aca

I suspect that we may need to veto the Dhcp6Dxe driver.

**Comment by mcb30** [comment]
Filed a bug against EDK2: https://bugzilla.tianocore.org/show_bug.cgi?id=4754

**Comment by mcb30** [comment]
@sprootik Should now be fixed: the driver veto in #1194 works around the EDK2 bug.

**Comment by sprootik** [comment]
You did a great job, thank you.

**Comment by mcb30** [comment]
> You did a great job, thank you.

Thank you, it's really nice to be appreciated!

**Comment by NiKiZe** [comment]
To make it clear, new location of original issue after migration from bugzilla: https://github.com/tianocore/edk2/issues/10506

**Comment by NiKiZe** [comment]
I have tried to reproduce this just to compare to #1358 but is not able to ...
Checking out and building 40b51124400df9cb0c with gcc15 fixes on top
```
$ qemu-system-x86_64 --version
QEMU emulator version 10.2.0
```
I assume then it was a 8. version of qemu, but since this is an EDK2 issue I would expect it to not really matter?

My test is:
```bash
qemu-system-x86_64 \
-enable-kvm \
-m 1024 \
-M q35 \
-cpu host     \
-bios /usr/share/edk2/OvmfX64/OVMF_CODE.fd \
-netdev tap,id=net0,ifname=tapv6boot,script=no,downscript=no \
-device virtio-net-pci,netdev=net0,romfile= \
-nographic
```
Any ideas on what I should do differently to have this issue re-appear?
My next step would then be to take current master, revert the veto and verify that/if it still hangs.

```
>>Start PXE over IPv6..
  Station IP address is 2001:DB8:0:0:0:0:0:12F
  Server IP address is 2001:DB8:0:0:0:0:0:1
  NBP filename is ipxe.efi
  NBP filesize is 1005056 Bytes
 Downloading NBP file...

  NBP file downloaded successfully.
iPXE initialising devices...



iPXE 1.21.1+ (g7554d) -- Open Source Network Boot Firmware -- https://ipxe.org
Features: DNS HTTP iSCSI TFTP VLAN SRP AoE EFI Menu

net0: 52:54:00:12:34:56 using MNP on MNP-0000:00:02.0 (Ethernet) [open]
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 52:54:00:12:34:56).......
```
Configuration fails and nothing on `show ip6` so something fails in iPXE, but it is not the freeze that I was expecting.
