### ISSUE TITLE
Network interface ordering

### ISSUE THREAD

**Issue by champtar** [ipxe/ipxe#1199]
Not sure if this is expected, the interfaces are a bit out of order (both when using ipxe.efi and snp.efi)
NIC is `Broadcom NetXtreme Gigabit Ethernet (BCM5720)`
https://www.dell.com/en-sg/shop/dell-quad-port-1-gigabit-broadcom-5720-network-daughter-card-cuskit/apd/540-bbhg/wifi-and-networking

![rpviewer (23)](https://github.com/ipxe/ipxe/assets/3536755/8ac8c24b-91ed-44a2-a552-c0e8a9f1369e)
![rpviewer (24)](https://github.com/ipxe/ipxe/assets/3536755/c2f2d113-7e5e-4e0f-95d5-69fce6850529)

**Comment by NiKiZe** [comment]
Just as in linux, the enumeration order is undefined. Specificly it enumerates drivers, and than each NIC for that driver.

Could you explain what kind of issue this is causing you?

**Comment by champtar** [comment]
> Just as in linux, the enumeration order is undefined. Specificly it enumerates drivers, and than each NIC for that driver.

In Linux you have Consistent Network Device Naming so enumeration order doesn't matter that much
what surprises me here is that it doesn't scan PCI buses in order (19 ends up before 18)

> Could you explain what kind of issue this is causing you?

I was just expecting to have port 1 == net0, I can work around this,
I just wanted to be sure this is expected in this case (here we only have 1 driver)

**Comment by NiKiZe** [comment]
In linux the order is defined by the order of loaded drivers, which is mostly alphabetical as long as you keep them in kernel and not modules... The (un)predictable network names just creates more problems and makes this very defined behaviour unpredictable between hosts /rant

Using snponly.efi when chained gives you one nic which it was booted from, other than that we can't be sure of ordering, you might be able to grab dmi data to get port designators and sort on that, but that would need to be in a script to not break any already existing assumptions on net ordering.

**Comment by habetsm-xilinx** [comment]
The PCI enumeration order will also vary between different BIOS vendors.
