### ISSUE TITLE
Menus with Items Display Off over COM ports

### ISSUE THREAD

**Issue by ericspidledw** [ipxe/ipxe#1259]
![image](https://github.com/user-attachments/assets/35a80e22-3cec-41e4-996a-0dfe2ed8c205)
![image](https://github.com/user-attachments/assets/d847d450-f871-479e-8bd2-30c31fb317d5)

When using iPXE menu's over a COM port the lines with items on them seem to be off some pixels and there are also some extra background color pixels above and below the menu itself. Not entirely sure what causes this and I know the ipxe commands are fine because on a real display these menus show up as expected

**Comment by ericspidledw** [comment]
The bottom one is my own custom menu and the top one I took from the NIC config choice example [here ](https://gist.github.com/robinsmidsrod/3871687)just to make sure it wasn't my specific menu configuration

**Comment by stappersg** [comment]
_`acknowledge`_ on the observation. Please express what are the expections from the `iPXE`-project. (In other words: Please explain why this issue should remain open.)

**Comment by NiKiZe** [comment]
When using serial, there is only text. (Pixels becomes a confusing term)
This might as well be a bug in your serial terminal.
Which terminal are you using, and what size does the terminal window have, is it exactly 80x25 or something else? (If not exactly the same as native, it is quite common with a number of rendering issues)
Also is this thru iPXE native serial support, or thru you bios/firmware serial console?

Problem description as I see it, menu items lacks the background color in the last column, there is also other places where background color is missing over serial.

**Comment by mcb30** [comment]
Your serial terminal emulator is failing to apply the background colour when clearing the screen, so that you end up with only the explicitly drawn characters having a background.

What serial terminal emulator are you using?

**Comment by NiKiZe** [comment]
Thanks for the info, closing as it's not an issue with iPXE
