### ISSUE TITLE
How to boot windows (iscsi) ?

### ISSUE THREAD

**Issue by ubun222** [ipxe/ipxe#1290]
I used to install windows11 in iscsi by using modified boot.wim but after two reboot it seem can’t reconnect to iscsi and throw “inaccessible boot device”.
In my case, WinPE(boot.wim) can recognize iscsi but it fails to boot essential system in iscsi.
I have tried to add package (WinPE-StorageWMI) to install.wim and X:\Windows but obviously it only works on PE.wim.
Is there any way to boot or it’s impossible in windows 11

**Comment by NiKiZe** [comment]
There is several discussions on iscsi windows boot, use the search function to find them.

This is not an iPXE issue.

**Comment by Hellomik2002** [comment]
@ubun222  did you find any solution ?

**Comment by NiKiZe** [comment]
> [@ubun222](https://github.com/ubun222) did you find any solution ?

You won't get much better than #1544 
There is a few different issues and discussions on the topic, main problem being that it is multiple.
If someone is to create a howto about what does work in discussions that would be great, otherwise keep to the already existing threads.
