### ISSUE TITLE
Consider changing mozilla certdata.txt link to https on ipxe.org/crypto

### ISSUE THREAD

**Issue by mcsaucy** [ipxe/ipxe#153]
Sorry if there's a better place to request this. I did a quick look and couldn't find any obvious place, and couldn't find a way to update this myself.

Anyway, ipxe.org/crypto links to [Mozilla list of public CA certificates](http://mxr.mozilla.org/comm-central/source/mozilla/security/nss/lib/ckfw/builtins/certdata.txt). That page was hanging for me (but this seems intermittent; I didn't have issues yesterday), but surprisingly, the [https version](https://mxr.mozilla.org/comm-central/source/mozilla/security/nss/lib/ckfw/builtins/certdata.txt) loads very quickly. Additionally, that page redirects to [hg.mozilla.com](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt), so it may be worth it to just point at that.

IDK if you're able to introduce this behavior, but if so, it may be worth making that change.

**Comment by mcb30** [comment]
Done; thank you!
