### ISSUE TITLE
[EFI] Assertion failures when kernel is about to be booted

### ISSUE THREAD

**Issue by toreanderson** [ipxe/ipxe#159]
Since commit c70b3e04e86cefca335e36f883829d89583a6921 iPXE is no longer able to boot my HP ProLiant DL380 Gen9 server with HPE Ethernet 10G 2-port 546FLR-SFP+ (rebranded Mellanox Technologies MT27520 Family [ConnectX-3 Pro]).

It fails like this, where it hangs until manually rebooted:

```
ASSERT u:\MdeModulePkg\Core\Dxe\Hand\Locate.c(492): Size >= 0
ASSERT u:\MdePkg\Library\BaseMemoryLibRepStr\CompareMemWrapper.c(62): (Length - 1) <= (0xFFFFFFFFFFFFFFFFULL - (UINTN)DestinationBuffer)
ASSERT u:\MdePkg\Library\BaseMemoryLibRepStr\CompareMemWrapper.c(63): (Length - 1) <= (0xFFFFFFFFFFFFFFFFULL - (UINTN)SourceBuffer)
ASSERT u:\MdeModulePkg\Core\Dxe\Hand\Locate.c(492): Size >= 0
ASSERT u:\MdePkg\Library\BaseMemoryLibRepStr\CompareMemWrapper.c(62): (Length - 1) <= (0xFFFFFFFFFFFFFFFFULL - (UINTN)DestinationBuffer)
ASSERT u:\MdePkg\Library\BaseMemoryLibRepStr\CompareMemWrapper.c(63): (Length - 1) <= (0xFFFFFFFFFFFFFFFFULL - (UINTN)SourceBuffer)
```

These messages appear after iPXE has completed the download the kernel and the initramfs image, and is about to hand over control to the Linux kernel.

Today's Git master with c70b3e04e86cefca335e36f883829d89583a6921 reverted works fine. When this build boots successfully, normal output from the Linux kernel appears instead of the ASSERT lines quoted above.

**Comment by pmounsey** [comment]
Same Gen10, HP FlexFabric 10Gb 2port 534FLR-SFP+ Adapter, after a few moments, RSOD GeneralProtectionException.    Also reverted to an older binary resolved issue.

![GeneralProtectionExceptoin](https://user-images.githubusercontent.com/25214766/96358254-1f0cab80-10d3-11eb-89c9-9968d04a0612.png)

**Comment by mcb30** [comment]
Commit https://github.com/ipxe/ipxe/commit/5b41b9a80 may fix the underlying issue.  @toreanderson: could you possibly retest with current master?  Thanks.

**Comment by toreanderson** [comment]
I will, but it might take a few more days before I get the opportunity, as the server is currently back in production and cannot be easily rebooted.

**Comment by NiKiZe** [comment]
Possible related to #164 (?)

**Comment by Cellebyte** [comment]
@toreanderson I tested it today with the current master and still got an issue.
I will append all stacktraces I got.
![pxe error](https://user-images.githubusercontent.com/16540824/98352979-01ba6580-201f-11eb-8508-2a3e344b91a5.PNG)
![pxe error 2](https://user-images.githubusercontent.com/16540824/98352973-fff0a200-201e-11eb-8d62-788c3cb63cd8.PNG)
![pxe error 3](https://user-images.githubusercontent.com/16540824/98352977-0121cf00-201f-11eb-9818-143b7d2a14fa.PNG)

Servers:
HPE ProLiant DL20 Gen10
HPE ProLiant DL325 Gen10 Plus

**Comment by toreanderson** [comment]
@mcb30 I have finally been able to re-test, and I can confirm that 5b41b9a80ffb365376d8d522675a8d248a8717ab (and master as of 0e26220902592fb3066d2043dec212d957215b79) resolves the assertion failures I saw previously, and I can boot my server without any problems.

I am however not closing this issue in case you would like to track @Cellebyte's boot failure here as well.

**Comment by mcb30** [comment]
> @mcb30 I have finally been able to re-test, and I can confirm that [5b41b9a](https://github.com/ipxe/ipxe/commit/5b41b9a80ffb365376d8d522675a8d248a8717ab) (and master as of [0e26220](https://github.com/ipxe/ipxe/commit/0e26220902592fb3066d2043dec212d957215b79)) resolves the assertion failures I saw previously, and I can boot my server without any problems.
> 
> I am however not closing this issue in case you would like to track @Cellebyte's boot failure here as well.

Fantastic; thank you for letting me know!

I will mark this issue as closed.  @Cellebyte please open a new issue if needed; thank you.

**Comment by Cellebyte** [comment]
@mcb30 going back to v1.20.x from January solved the issue for me.

**Comment by mcb30** [comment]
@Cellebyte The underlying issue should be fixed as of commit 1295b4acf - please try retesting with the current iPXE master.  Thank you!

**Comment by Cellebyte** [comment]
@mcb30 thanks I will test it when I'am back from vacation ^^

**Comment by kjetilho** [comment]
I had the same problem as @Cellebyte on a HPE DL380 gen10, upgrading to iPXE 1.20.1+ (gb6e2e) fixed the problem.
