### ISSUE TITLE
Pressing Ctrl-B on iMac boots into MacOS instead of opening command line.

### ISSUE THREAD

**Issue by KingDiamondDev** [ipxe/ipxe#161]
When I boot iPXE.efi, the Mac initially shows that it is configuring the network adapters, then asking me to hit Control B. I strike the keys, but then it boots to MacOS 10.14. Any idea why?

**Comment by NiKiZe** [comment]
Due to how iPXE tries to detect Ctrl it might not work on all EFI implementations, as a workaround there is Esc, B

**Comment by NiKiZe** [comment]
Did ESC, B work?

If it did, or if you abandoned the quest please close the issue. If it didn't please provide us with that information.

**Comment by KingDiamondDev** [comment]
Oh shoot I apologise. Yes, Esc+B did work. Thank you very much!

**Comment by NiKiZe** [comment]
Perfect, thanks!
