### ISSUE TITLE
Cross signed certificate missing DigiCertHighAssuranceEVRootCA

### ISSUE THREAD

**Issue by aarnaud** [ipxe/ipxe#183]
There is a new certificate valid unitl 2031 that not present http://ca.ipxe.org/cross/

https://cacerts.digicert.com/DigiCertHighAssuranceEVRootCA.crt.pem

**Comment by mcb30** [comment]
The cross-signed certificate list is generated monthly from the Mozilla trusted certificate list at https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt

Please reopen if the certificate is present in this list but does not appear as expected at the next monthly run (on January 1st).

Thanks
