### ISSUE TITLE
Chainloaded DHCP options for UEFI

### ISSUE THREAD

**Issue by mcb30** [ipxe/ipxe#188]
## Description

As a user, I want UEFI chainloading to work similarly to BIOS chainloading, to minimise my surprise.  In particular, I would like options from the original vendor PXE DHCP request to be available within UEFI iPXE as they are in BIOS iPXE.

## Acceptance criteria

- [x] Ability to chainload `snponly.efi`, to break immediately into the iPXE shell via Ctrl-B, and to see via `route` that iPXE already has an IPv4 address configuration
- [x] Ability to chainload `snponly.efi`, to break immediately into the iPXE shell via Ctrl-B, and to see `show filename` show the path to `snponly.efi` itself.

**Comment by etnestad** [comment]
> * [ ]  Ability to chainload `snponly.efi`, to break immediately into the iPXE shell via Ctrl-B, and to see `show filename` show the path to `snponly.efi` itself.

What do you mean by path in this context? tftp://<server-ip>/snponly.efi ?

**Comment by mcb30** [comment]
> > * [ ]   Ability to chainload `snponly.efi`, to break immediately into the iPXE shell via Ctrl-B, and to see `show filename` show the path to `snponly.efi` itself.
> 
> What do you mean by path in this context? tftp://server-ip/snponly.efi ?

It would be whatever was present in the boot filename as provided by DHCP (i.e. matching the behaviour that already exists for BIOS builds).

**Comment by etnestad** [comment]
> > > * [ ]    Ability to chainload `snponly.efi`, to break immediately into the iPXE shell via Ctrl-B, and to see `show filename` show the path to `snponly.efi` itself.
> > 
> > 
> > What do you mean by path in this context? tftp://server-ip/snponly.efi ?
> 
> It would be whatever was present in the boot filename as provided by DHCP (i.e. matching the behaviour that already exists for BIOS builds).

Ah, got it!

**Comment by etnestad** [comment]
A couple of questions:

For now I have just written some test code in efi_init.c to invoke pxe_base_code_protocol to get the cached DHCP packet. Where is the "right" location for this code?

What mechanism should I use to configure the network interface with the information from the cached DHCP packet?

**Comment by mcb30** [comment]
@etnestad Thanks.  It required some slightly complex restructuring to allow code to be shared between BIOS and UEFI, so I've implemented it myself.
