### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by chainofhonor** [ipxe/ipxe#189]
util/zbin.c:7:18: fatal error: lzma.h: No such file or directory

how to solve this problem?

i want to use undionly.kpxe
but i don't know the default config filename
i create a file named demo.ipxe  it doesn't work

**Comment by NiKiZe** [comment]
https://forum.ipxe.org/showthread.php?tid=7730 has the same error and explanation.

**Comment by mcb30** [comment]
For the benefit of future searchers: you need to install the liblzma development headers, which are usually in a package called something like `liblzma-dev` or `xz-devel`
