### ISSUE TITLE
Impossible to make the installation work

### ISSUE THREAD

**Issue by timmarinus** [ipxe/ipxe#202]
Hello,
I am trying to install the IPXE latest because we run in to issues with the version supplied with YUM install on centos 7.

When i try to follow the installation steps on this github i run in to the first error, that GCC command is not found. I installed GCC using yum install GCC. after this i tried in the folder src the command make. 
but that resulted in the following error see below.

Error: 
In file included from include/ipxe/fault.h:13:0,
                 from core/fault.c:28:
./config/fault.h:32:32: fatal error: config/local/fault.h: No such file or directory

![image](https://user-images.githubusercontent.com/50841438/104022540-b65c3900-51c0-11eb-9e2c-0c2f64e84bf7.png)

Can somebody help me by telling me what i do wrong, the reason we want to update and try is with version 20.18 (installed via YUM on centos 7) we run in to the issue a lot of nodes keep getting completly stuck and is fixed by rebooting the de device (sometimes multiple reboots are necessary) we hope that this is fixed in the new version, we need this for a automatic installation of OpenShift cluster.

Thanks in advance!
Tim

**Comment by NiKiZe** [comment]
If you don't have all tools install and build you sometimes get an invalid src structure. Try to remove ipxe and do a fresh git clone. This is not an issue with ipxe, so will be closing. Should be better as a discussion, but feel free to respond and will try to help.
