### ISSUE TITLE
Error: No bootable device 

### ISSUE THREAD

**Issue by Hablok** [ipxe/ipxe#237]
I installed the Windows 2003 server on the qemu emulator. After the first shutdown using VNC Viewer I can't get there. At first It started writing that this port is not listenening. Then I entered command qemu-system-i386. After that I was able to connect, but instead of Windows there was written NO BOOTABLE DEVICE. How to fix it? How can I start the system again?

**Comment by NiKiZe** [comment]
Well, that is a problem with you disk, or VM. Not related to iPXE (so closing this), but do feel free to use discussions (instead of creating issues) if you need help or have questions about iPXE.
