### ISSUE TITLE
Unload of SnpOnly.efi at  UEFI shell leads to hang or crash when map -u is executed later

### ISSUE THREAD

**Issue by k-s-srikanth** [ipxe/ipxe#317]
Hi 
We are using the snpOnly.efi (downloaded from iPXE.org). Our requirement is to use the network stack after download few files from the server using SnpOnly.efi. 
Since SnpOnly is using the Network stack until it is present, we try to unload the same using "unload" command on UEFI shell. 
Once this is done, we do connect -r and get back the network. 
But after unload, execution of "map -u" or "map -r" is either hanging / crashing. 
From the open source code of the iPXE.org, we see that efi_unload() is disconnecting all the drivers / protocols, once unload of SnpOnly is done. 
Next execution of "map -u/-r" command will hang/crash as it was dependent on many protocols like BlockIO protocol that was uninstalled along with unload command. 
Can someone help me how to go about it.

**Comment by mcb30** [comment]
UEFI in general does not gracefully handle unloading of anything.  Most vendor UEFI implementations have bugs that prevent unloading from working.  I would suggest that you rethink your workflow to avoid the need to unload `snponly.efi`.
