### ISSUE TITLE
Building bad legacy BIOS iso image

### ISSUE THREAD

**Issue by JuniorJPDJ** [ipxe/ipxe#405]
I'm trying to create ISO image working on both, EFI and legacy bios using your script `./util/genfsimg`.
I ended up having working disk image on all supported platforms and ISO image working on all EFI platforms and breaking on legacy BIOS.
Am I missing something or is this a bug?
ISOLINUX based image complains about ldlinux.c32 missing when booting, but SYSLINUX image is working correctly.

Legacy BIOS, SYSLINUX based disk image:
![Screenshot_20210708_055241](https://user-images.githubusercontent.com/7334549/124859752-b6db5e00-dfb0-11eb-948c-ee7d0e2f9080.png)

Legacy BIOS, ISOLINUX based CD/disk image (fails when booting from CD-ROM and when booting as disk):
![Screenshot_20210708_055345](https://user-images.githubusercontent.com/7334549/124859855-e1c5b200-dfb0-11eb-8428-ac741bfa09c3.png)

Script I used to make images (and build iPXE):
https://git.juniorjpdj.pl/rootownia/docker/netboot/-/blob/master/ipxe-builder/build.sh
Dependencies I installed before building:
https://git.juniorjpdj.pl/rootownia/docker/netboot/-/blob/master/ipxe-builder/Dockerfile

**Comment by NiKiZe** [comment]
Your script is to complex to try and figure out what is going on.
Could your post a minimal script that shows the issue?

If possible also include qemu commandline that can be used to test the 2 modes.

**Comment by JuniorJPDJ** [comment]
Run clean debian and:
```
$ apt update -y
$ apt install -y --no-install-recommends build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi wget ca-certificates liblzma-dev xorriso syslinux isolinux syslinux-utils mtools
```

build some iPXE images for targets:
bin-i386-pcbios/ipxe.lkrn bin-i386-efi/ipxe.efi bin-x86_64-efi/ipxe.efi bin-arm32-efi/snp.efi bin-arm64-efi/snp.efi

then try to create iso:

```
./util/genfsimg -o netboot.iso bin-i386-pcbios/ipxe.lkrn bin-i386-efi/ipxe.efi bin-x86_64-efi/ipxe.efi bin-arm32-efi/snp.efi bin-arm64-efi/snp.efi
```

I've no QEMU cmdline to run it, just try booting it on ANY legacy bios system or VM, it'll fail.

**Comment by mcb30** [comment]
> ```
> ./util/genfsimg -o netboot.iso bin-i386-pcbios/ipxe.lkrn bin-i386-efi/ipxe.efi bin-x86_64-efi/ipxe.efi bin-arm32-efi/snp.efi bin-arm64-efi/snp.efi
> ```
> 
> I've no QEMU cmdline to run it, just try booting it on ANY legacy bios system or VM, it'll fail.

The above works fine for me on Fedora.

The most likely explanation is that you either do not have `ldlinux.c32` installed on your build host, or that Debian places it in a location that `genfsimg` does not search for: https://github.com/ipxe/ipxe/blob/4d180be5175e176ec27680557c1d67536a847610/src/util/genfsimg#L95-L106

If it's the latter, then please let us know where this file gets placed on Debian (or submit a PR that adds the relevant path).

**Comment by JuniorJPDJ** [comment]
Well. It was my bad.
I was sure `ldlinux.c32` is also needed for USB images, but it was not.
It was entirely missing from my system as it's in `syslinux-common` package, which.. well.. is not being installed in dep to `syslinux` or `isolinux` which is weird.
Now it works.
Thanks for attention and help :D
