### ISSUE TITLE
Document "cpuvendor", "cpumodel", and "CPUID_SETTINGS"

### ISSUE THREAD

**Issue by PicoMitchell** [ipxe/ipxe#419]
I only just noticed these variables exist when looking at recent commits and saw them used here: https://github.com/ipxe/ipxe/commit/4d180be5175e176ec27680557c1d67536a847610

I double checked and these are not mentioned on https://ipxe.org/cfg

The documentation for "cpuvendor" and "cpumodel" could be very similar to https://ipxe.org/cfg/memsize and state that they require "CPUID_SETTINGS" which would also require adding documentation for that similar to https://ipxe.org/buildcfg/memmap_settings.

As always, thank you so much for iPXE!

**Comment by NiKiZe** [comment]
Best source for documentation is probably https://ipxe.org/cmd/config

**Comment by PicoMitchell** [comment]
That won't show settings that  weren't enabled during build though, right?

The issue here was that I didn't even know to enable "CPUID_SETTINGS" since I didn't know the "cpuvendor" and "cpumodel" existed.

Even when I did learn they existed, I had to read the source code to figure out how to enable them. Other users may not have been able to understand that code and wouldn't have know how to enable them without some documentation like there is for other settings.

**Comment by mcb30** [comment]
Good point, and thank you for suggesting which existing documentation could most sensibly be used as a template.  I have added documentation for these at https://ipxe.org/cfg/cpumodel, https://ipxe.org/cfg/cpuvendor, and https://ipxe.org/buildcfg/cpuid_settings - please review and reopen if there are any issues.
