### ISSUE TITLE
Attempting to make 32 bit arm uefi image results in never ending search for dependencies.

### ISSUE THREAD

**Issue by rustyscottweber** [ipxe/ipxe#472]
```
nohup make ARCH=arm32 bin-arm32-efi/ipxe.efi &
```
Build process goes forever and will never end. See attached nohup.out file for details on very repetitive output.

[nohup.out.txt](https://github.com/ipxe/ipxe/files/7199804/nohup.out.txt)

**Comment by rustyscottweber** [comment]
Looks like this is only while attempting to cross compile.  Attempting to build this target on a 32bit arm device results in a successful build.

**Comment by NiKiZe** [comment]
Have you made any modifications to configurations or similar? and did you try with `make V=1` ?

**Comment by rustyscottweber** [comment]
No modifications. I have not yet tried using V=1. However, adding an additional parameter for centos (May differ for ubuntu/debian):
```
CROSS_COMPILE=arm-linux-gnu-
```
seems to allow the build to get much further. It still doesn't build, but at least I get the same error that I do on a native build.

**Comment by rustyscottweber** [comment]
Looks like this was something screwy with my build environment. After attempting with the cross compile parameter, I can no longer reproduce the issue. Closing issue, but maybe this will help posterity.
