### ISSUE TITLE
Request getting triage access and apply/dismiss existing labels

### ISSUE THREAD

**Issue by berlin4apk** [ipxe/ipxe#484]
I would like to help the project with doing work on Managing labels.
For this I like to get triage access.
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by stappersg** [comment]
Quoting https://sfconservancy.org/GiveUpGitHub/
> GitHub itself is the very opposite of FOSS. By contrast, Git was designed [specifically to replace a proprietary tool (BitKeeper)](http://www.h-online.com/open/features/The-saga-of-Git-Lightning-does-strike-twice-1051559.html), and to make FOSS development distributed — using FOSS tools and without a centralized site. GitHub has warped Git — creating add-on features that turn a distributed, egalitarian, and FOSS system into a centralized, proprietary site. And, all those add-on features are controlled by a single, for-profit company. By staying on GitHub, established FOSS communities bring newcomers to this proprietary platform — expanding GitHub's reach. and limiting the imaginations of the next generation of FOSS developers.
