### ISSUE TITLE
X550 nic not recognized on Gigabyte motherboard in UEFI mode

### ISSUE THREAD

**Issue by Keno** [ipxe/ipxe#503]
I have a Gigabyte MZ42-G20 motherboard with onboard intel X550 NICs.
I built iPXE from master and used the BMC's Virtual CDROM drive feature to
attach this iso to the machine. This boot succesfully into iPXE, but `ifstat` shows
no network devices. Following https://github.com/ipxe/ipxe/issues/156, I rebuilt with
`make DEBUG=efi_driver,efi_pci,snpnet bin-x86_64-efi/intelx.iso`, which produced the following debug output:
![Screenshot from 2021-10-25 20-28-26](https://user-images.githubusercontent.com/1291671/138788836-8bfbfc51-9aec-4338-a256-32f2c69cb85f.png)
![Screenshot from 2021-10-25 20-30-13](https://user-images.githubusercontent.com/1291671/138788888-65d64d81-d806-47e6-9d78-56550a7deabd.png)

My apologies for the poor quality screenshot - I'm connecting through a rather janky BMC console. I believe the relevant output from the above is:

```
EFIDRV PciRoot(0x3)/Pci(0x3,0x4)/Pci(0x0,0x0) could not disconnect existing drivers: Error 0x7f37e08e
```
and
```
EFIPCI PciRoot(0x3)/Pci(0x3,0x4)/Pci(0x0,0x0) could not open PCI device: Error 0x7f10e18f
```

I will note that this is with master, i.e. in particular with the commit 9b25f6e by @mcb30 that resolved ipxe/ipxe#156, so I believe this is a different issue.

**Comment by ITJamie** [comment]
just a note. ive experienced this on recent asrock boards too for the x550-at2 nic's. ive not yet found a bios upgrade that fixes the issue

**Comment by NiKiZe** [comment]
> > ive not yet found a bios upgrade that fixes the issue
> 
> It's not a BIOS upgrade, it's a NIC firmware upgrade that's required

If NIC is onboard it usually don't have its own ROM, In that case it is the board BIOS/Firmware that can provide a fix, but it requires that the flash file has the updated firmware.

**Comment by Keno** [comment]
> If NIC is onboard it usually don't have its own ROM, In that case it is the board BIOS/Firmware that can provide a fix, but it requires that the flash file has the updated firmware.

All the X550 boards I've seen had a separate flash chip for the NIC firmware. I suspect that's because the firmware is required to bring up the NC-SI, which needs to work with a corrupt BIOS (or no main CPU to run the BIOS).

**Comment by Keno** [comment]
For my own and others' future reference (since I just had the same issue again on a different machine), the way to update the NIC firmware is as follows:
```
wget https://downloadmirror.intel.com/727462/X550_NVMUpdatePackage_v3_60.zip
tar xzf X550_NVMUpdatePackage_v3_60_Linux.tar.gz
cd X550/Linux_x64
sudo ./nvmupdate64e
```
