### ISSUE TITLE
Wrong TPL when returning from unload of iPXE EFI driver

### ISSUE THREAD

**Issue by pe-bo** [ipxe/ipxe#520]
The Unload function (efi_unload) is called with TPL_APPLICATION and this function calls shutdown callbacks. One of them is tcp_shutdown which calls currticks (actually efi_currticks). Normally the function restores TPL to external TPL (TPL_APPLICATION) and raises back to TPL_CALLBACK. But for EFI driver builds the assumption of a TPL on enter is not met.

This is manifested, for example, by the failure of the WaitForEvent function in an application launched after the driver unload. The problem can be easily demonstrated in the UEFI shell - the first unload command asks (y / n), the second no longer. 

iPXE EFI application builds do not have this problem because shutdown callbacks are called under efi_snp_claim which raises TPL to TPL_CALLBACK itself.

**Comment by mcb30** [comment]
Good catch!  Should be fixed in https://github.com/ipxe/ipxe/commit/a046da21a

Thanks!
