### ISSUE TITLE
ISCSI protocol usage issues in UEFI Shell environment

### ISSUE THREAD

**Issue by kkimdong** [ipxe/ipxe#523]
Hi guys,

I need help running my UEFI PXE server.

Booting to UEFI Shell was successful using PXE Bootloader (ipxe.efi ver 1.21.1).

UEFI Shell is a Diskless environment, which is connected by the ISCSI protocol.

The Problem is

 When copying or saving 1.txt (File size : 1Byte) file in UEFI Shell of the client PC, it takes a lot of time, about 2-3 minutes.

Any way to solve this?

 
PS: There is no problem in saving or copying 1.txt file after iSCSI connection in Windows 7 environment.

https://user-images.githubusercontent.com/19599744/143183108-76449885-37f3-4354-91a5-e9ea5f5c6143.MOV

**Comment by NiKiZe** [comment]
Use a packet capture to try and figure out what is going on.

**Comment by kkimdong** [comment]
> Use a packet capture to try and figure out what is going on.

Hi

In the picture file, I can see that the TCP Protocol is repeatedly displayed slowly on the screen.

What should i do? Please let me know

![D82209B3-37C5-460E-99AE-9B1CA1573CEF](https://user-images.githubusercontent.com/19599744/143188145-84673770-e620-4d2a-82e5-ac8f6323695a.png)

**Comment by mcb30** [comment]
The UEFI shell is not generally usable for creating files.  I have frequently observed similar problems on other filesystems (e.g. a physically attached USB key).

Why are you trying to create a file on the iSCSI disk from within the UEFI shell?

**Comment by kkimdong** [comment]
Hi~
We test Memory like Memtest86 program in environment UEFI Shell. 
I have confirmed that there is no problem when saving or copying files in UEFI Shell environment using iSCSI function in Server's BIOS menu.
Is there a way to copy or save in UEFI Shell after iSCSI protocol connection using PXE?

**Comment by mcb30** [comment]
It should in theory work, but the whole block device layer in iPXE is optimised for reading rather than writing.  In a typical OS boot, at most one 512-byte write occurs to the SAN device.  To reduce code size, iPXE doesn't bother trying to make this unusual case fast.

**Comment by kkimdong** [comment]
A static IP address of 192.168.0.255 was set on the client PC.
After PXE booting, it was confirmed that when ISCSI is connected, it runs normally.
Only static IP address 192.168.0.255 is running normally
Other IP addresses do not work

Can you find a workaround with the above method?

**Comment by mcb30** [comment]
> A static IP address of 192.168.0.255 was set on the client PC. After PXE booting, it was confirmed that when ISCSI is connected, it normal operation. Only static IP address 192.168.0.255 is running normally Other IP addresses do not operation

That IP address does not appear to be valid.  Addresses in 192.168.0.x would most usually be used with a subnet mask of 255.255.255.0.  With that subnet mask, the address 192.168.0.255 is the broadcast address, and cannot be assigned as an individual IP address.

Marking this issue as closed since there does not appear to be any clear topic.
