### ISSUE TITLE
Lenovo T14 iPXE boot failed

### ISSUE THREAD

**Issue by smallfish01** [ipxe/ipxe#609]
Hello,
I have a new  laptop and like to install Windows 10 from iPXE server, when I boot laptop from iPXE it can be get IP address from DHCP server, but the next step get error: "net1 link down" and cannot install OS from iPXE server, do you know why?

My laptop NIC is Realtek RTL8111H-CG.

Please check the screenshot.
![image](https://user-images.githubusercontent.com/4077255/157410786-b02215ff-d86d-47ac-88ac-98e7528a773e.png)

DHCP server log:
![image](https://user-images.githubusercontent.com/4077255/157411370-ec717b24-055e-43e4-8330-dbf02b9bd2f9.png)

Thank you so much.

**Comment by NiKiZe** [comment]
Exactly which model? Having several T14 (Intel) that works fine.
You seem to have blured out some details, which makes me believe that you are not using official iPXE, and also are not using latest version.

Please try latest ipxe.efi from boot.ipxe.org

**Comment by smallfish01** [comment]
Hello,
ThinkPad T14 AMD Gen 2,  CPU：AMD Ryzen 5 PRO 5650U 2.3Ghz. 
I pasted two new screenshots as below, please have a look, also I will update the latest version later.
![image](https://user-images.githubusercontent.com/4077255/157580674-9b599c4a-53d9-4e7f-97f8-dfcbad1c5a8f.png)
![image](https://user-images.githubusercontent.com/4077255/157580769-11b2682e-79f6-437d-8f10-90306dfb5d29.png)

**Comment by NiKiZe** [comment]
Will not even try to debug this, run latest pure iPXE and reproduce.

**Comment by smallfish01** [comment]
Hello, 
Just download the latest iPXE and verify, it works.

So the reason is iPXE does not have laptop NIC driver?

Thank you so much.

**Comment by NiKiZe** [comment]
You downloaded the latest iPXE which works?, then the issue have eighter been fixed in a later version. Or your other builds are broken.

So not a current issue with iPXE, correct?

**Comment by smallfish01** [comment]
Sure. I downloaded the latest iPXE(V1.21.1) then my new laptop can boot from iPXE and install Windows OS,  so the latest iPXE works for T14 laptop.

Thank you so much.

**Comment by NiKiZe** [comment]
Awesome!
