### ISSUE TITLE
Getting IP via DHCP fails on 82599-vf over ovmf UEFI

### ISSUE THREAD

**Issue by IriKaQ** [ipxe/ipxe#646]
I want to passthrough 82599-vf to the virtual machine, and then do remote boot through iPXE. The following phenomena were found:

1. When I use ovmf UEFI firmware, I cannot get IP (default DHCP). The NIC ROM is `bin-x86_64-efi/808610ed.efirom`. Unable to ping the virtual machine from outside.
2. When using the ovmf UEFI firmware and `bin-x86_64-efi/ipxe.usb`, I have tried manually specifying the IP, but it doesn't seem to work because the virtual machine cannot be pinged from outside.
3. When I switch BIOS to seabios and `bin/808610ed.rom`, I can get IP (default DHCP). The virtual machine can be pinged from the outside.
4. When I turn off spoof checking of vf, use ovmf UEFI firmware and `bin-x86_64-efi/808610ed.efirom`, I can get IP (default DHCP). The virtual machine can be pinged from the outside.

**Comment by NiKiZe** [comment]
Exactly which binary? Which version? And what message? (Did you follow the guidence from the link in the message?)
What does ifstat show after the failure?
(Use Ctrl-B and run dhcp followed by ifstat)

**Comment by IriKaQ** [comment]
Sorry for the late update, the main binary information has been updated, thanks.

**Comment by IriKaQ** [comment]
My other virtual machines (spoof checking is on) that pass through the pf NIC can be used in the system normally.

My VMs include Windows 10, Ubuntu 20.04, RockyOS 8.5 and etc.

**Comment by NiKiZe** [comment]
In the scenario where it does not work and you boot full OS, does ping work? (Please rule out all factors except for iPXE)

**Comment by IriKaQ** [comment]
> In the scenario where it does not work and you boot full OS, does ping work? (Please rule out all factors except for iPXE)

Yes, it works.

**Comment by stappersg** [comment]
FWIW   Issue has been seen. Also seen _passthrough 82599-vf to the virtual machine_.

Not seen is why _iPXE team_ should allocate further resources to this issue.

Advise for @IriKaQ and all others who are bitten by the _undesired behaviour_, provide ways to reproduce this _"feature"_.  That in other words: Make **your** problem **our** challenge. (Yes, you are all invited to join the _iPXE team_.)

**Comment by NiKiZe** [comment]
Ok then, provide the information that was requested in my previous message.

**Comment by IriKaQ** [comment]
Something unexpected happened when I tried to reproduce and I can't reproduce it for now, maybe I need to do more experiments to confirm it.

**Comment by NiKiZe** [comment]
Closing until the requested information is documented.
