### ISSUE TITLE
Priority/order of embedded image and cmdline "image"?

### ISSUE THREAD

**Issue by jcaesar** [ipxe/ipxe#648]
In short: If you boot an ipxe image with an embedded script and command line parameters, the command line parameters are [registered](https://github.com/ipxe/ipxe/blob/1192edf394aaebde666c6aafda1c8b782b08a845/src/arch/x86/core/runtime.c#L157=) as the second image, and the embedded script is executed, disregarding the the parameters. Is this intended behaviour?

In long:
I've set up two scripts
```
#!ipxe
chain some-ipxe-with-embedded-script.pxe foobar
```
```
#!ipxe
echo Hello from embedded script
```
and embedded the second script in an image, which I additionally patched to print the registrered images at the [start of the boot flow](https://github.com/ipxe/ipxe/blob/70995397e5bdfd3431e12971aa40630c7014785f/src/usr/autoboot.c#L592=) and named it `some-ipxe-with-embedded-script.pxe`.

When running the first script 
```bash
qemu-system-x86_64 -m size=512 -nographic -device virtio-net-pci,netdev=n0 -netdev user,id=n0,bootfile=http://liftm.de/Misc/ipxe-image-order/chain-imgstat.ipxe
```
I get the following output
```
embed.ipxe : 46 bytes [script] [TRUSTED] [SELECTED]
<CMDLINE> : 45 bytes [script]
Hello from embedded script
```
i.e. it runs the embedded script and completely ignores the `foobar` argument passed in the first script. I find this counter-intuitive. Is this intended? Can I submit a patch?

**Comment by NiKiZe** [comment]
That is intended, an image with embedded script should only execute that, at least unless autoexec.ipxe exists. (In efi)

Please follow the autoboot logic which you can find in the sources.

We should also be clear here that any arguments are taken as iPXE commands and put in a script.
It is also possible to supply a script as an initrd if lkrn.
(Note that this only applies to pcbios)

**Comment by NiKiZe** [comment]
Also it didn't ignore cmdline, it generated the script, but the embedded script is still the selected. You should be able to chain the cmdline script from your embedded script if you need to.

**Comment by stappersg** [comment]
firstscript:
```text
#!/usr/bin/bash
nextscript foobar
```
nextscript:
```text
#!/usr/bin/bash
echo Hello from nextscript ${1}
```
@jcaesar go find the equivalent of `${1}` in _iPXE environment_.


Regarding
> Can I submit a patch?

Just try it and see what happens.

**Comment by jcaesar** [comment]
> Also it didn't ignore cmdline, it generated the script, but the embedded script is still the selected. You should be able to chain the cmdline script from your embedded script if you need to.

Oh, I hadn't thought of that, thank you. I can definitely add
```
echo Executing CMDLINE if present...
imgstat <CMDLINE> && imgexec -ar <CMDLINE> || echo
```
to the start of my embedded script.

> > Can I submit a patch?

> Just try it and see what happens.

Guess I'd need to find the relevant documentation page and its git repo first… *cough*
