### ISSUE TITLE
Additional PCI ID for intelxl (aka i40e)?

### ISSUE THREAD

**Issue by danmcd** [ipxe/ipxe#653]
A customer of ours was trying to iPXE boot (using the TritonDataCenter downstream `ipxe`) on a machine equipped with X710s with the PCI ID of 8086,15ff, and the machine would reboot before iPXE handed off control to illumos.  There is no entry for that in the intelxl.c file.  We need to be sure, but adding the line (per https://github.com/TritonDataCenter/ipxe/pull/11) may be all we needed.

**Comment by danmcd** [comment]
PR  #654

**Comment by stappersg** [comment]
On Wed, May 25, 2022 at 11:41:50AM -0700, Dan McDonald wrote:
> PR  #654 

Acknowledge.

Consider to close this issue.

**Comment by NiKiZe** [comment]
> Consider to close this issue.

No, keep it open and close when PR is merged (done automatically)

**Comment by NiKiZe** [comment]
Did we get this verified as working?

**Comment by danmcd** [comment]
It's now public in our downstream Triton ipxe that just hit our servers today (announcement tomorrow).  It's been passing regression-tests internally (with other i40e/intelxl NICs).

Our customer who requested this in the first place is running the affected hardware in production with an iPXE with my change in it.

So to answer your question, yes, our customer verified it.

**Comment by danmcd** [comment]
Note, the recent PR (and our own repo) had a typo (1599 vs. 15ff) that mismatched what we sent our customer (15ff).

**Comment by danmcd** [comment]
ANd we can close this since it appears to be fixed upstream.

**Comment by danmcd** [comment]
Closing as duplicate since it was fixed more properly by someone else.
