### ISSUE TITLE
Patches welcome label

### ISSUE THREAD

**Issue by stappersg** [ipxe/ipxe#696]
This issue is to request a  "patches welcome" label.

Usage for that new label is to signal _"Your change request has been seen, however it is not on our priority list. When some one provides a patch, that patch will be reviewed."_

The improvement for the iPXE project is having an alternative for the document http://www.catb.org/~esr/faqs/smart-questions.html that starts with _"In the world of [hackers](http://www.catb.org/~esr/faqs/hacker-howto.html), the kind of answers you get to your technical questions depends as much on the way you ask the questions as on the difficulty of developing the answer."_ and the more often used _silent treatment_.

**Comment by NiKiZe** [comment]
Constant non helpful and borderline rude posts. Closing.
