### ISSUE TITLE
Retry on different port

### ISSUE THREAD

**Issue by stappersg** [ipxe/ipxe#730]
Hi,

Seen in a packet capture:

```text
iPXE:  Hey Webserver, I want a TCP stream at port 15117
Webserver: Hi iPXE, we have already a stream at port 15117
iPXE: Okay Webserver, let us tear down our port 15117 stream
```
follow-uped by:
```text
iPXE:  Hey Webserver, I want a TCP stream at port 15117
Webserver: Hi iPXE, we have already a stream at port 15117
iPXE: Okay Webserver, let us tear down our port 15117 stream
```
plus **three** more:

```text
iPXE:  Hey Webserver, I want a TCP stream at port 15117
Webserver: Hi iPXE, we have already a stream at port 15117
iPXE: Okay Webserver, let us tear down our port 15117 stream
```
which resulted in a https://ipxe.org/err/4c0a60 _Connection timed out_.  ( https://github.com/ipxe/ipxe/discussions/704 )

This issue is for asking to improve _iPXE_ by doing _retries on different ports_.

**Comment by stappersg** [comment]
For your information, this issue is a retry of #710. Difference is that `Okay Webserver, we lets tear down our port 15117 stream` is being changed into `Okay Webserver, let us tear down our port 15117 stream`.

![afbeelding](https://user-images.githubusercontent.com/35434094/187169436-a07e10d0-f808-48bb-87a3-5b05c8a52880.png)

**Comment by NiKiZe** [comment]
Your spam is not acceptable

**Comment by stappersg** [comment]
![afbeelding](https://user-images.githubusercontent.com/35434094/187211272-3d05cfcc-07a6-4cc8-a7d8-ff8a24013cd9.png)


> Your spam is not acceptable

For the record:  I'm ignoring the personal attack.  At least for now. This issue is about getting retries on different ports. Improving iPXE.

Things that we have already records of:
* Issue #710 being closed with _"converted into a discussion"_ as **only** comment
* The silence in discussion #711
