### ISSUE TITLE
(patch) https://ipxe.org/download 

### ISSUE THREAD

**Issue by stappersg** [ipxe/ipxe#765]
> So again https://boot.ipxe.org/ipxe.usb !

Yes, however it is **not** _clickable_ from https://ipxe.org/download ( https://boot.ipxe.org/ipxe.iso is )

_Originally posted by @stappersg in https://github.com/ipxe/ipxe/discussions/757#discussioncomment-3787006_

More text to come ...

**Comment by stappersg** [comment]
_head_ of current 
```text
====== Download ======

===== Pre-built binaries =====

You can download a prebuilt binary version of iPXE as an ISO image from [[https://boot.ipxe.org/ipxe.iso]].  This image allows you to experiment with iPXE for the first time.  To use iPXE fully, you will need to build an appropriate image from source.
```

**Comment by stappersg** [comment]
With line breaks
```text
====== Download ======

===== Pre-built binaries =====

You can download a prebuilt binary version of iPXE as an ISO image from [[https://boot.ipxe.org/ipxe.iso]].
This image allows you to experiment with iPXE for the first time.
To use iPXE fully, you will need to build an appropriate image from source.
```

**Comment by stappersg** [comment]
That new text should solves #757, the biggest improved is probably that the first URL, https://boot.ipxe.org/ , brings an _index page_. So clicking on the new first URL does **not** start a download of a four Megabyte large `.iso`.

**Comment by NiKiZe** [comment]
Closing, this is not how to communicate, the way it is done here is pure spam.

**Comment by stappersg** [comment]
[june 2022](https://github.com/ipxe/ipxe/discussions/502#discussioncomment-3053568)
