### ISSUE TITLE
EFI cannot boot from SAN device 0 (anymore)

### ISSUE THREAD

**Issue by jensgw** [ipxe/ipxe#776]
I did not update iPXE for about a year. Booting from local disk worked fine with `sanboot --no-describe --drive 0`. Yesterday I did an update and now local boot does not work anymore. Error

EFIBLK cannot find drive 0x00
Boot from SAN device 0x00 failed No such device (https://ipxe.org/2c222087)

qemu/libvirt with ovmf

**Comment by jensgw** [comment]
Never mind, I am pretty sure I forgot to apply this patch series: https://lists.ipxe.org/pipermail/ipxe-devel/2019-February/006504.html

**Comment by jensgw** [comment]
Yeah it were the patches. But this feature would still be awesome in the actual release.

**Comment by stappersg** [comment]
This issue now has link to #612
