### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [ipxe/ipxe#904]
Dear @ipxe team,

Can you create a new version?

Already more two year since the last one: 1.21.1 (2020-12-31):
- https://github.com/ipxe/ipxe/tags

Thanks in advance.

Linked to:
- https://github.com/ipxe/ipxe/discussions/887
- https://github.com/ipxe/ipxe/issues/886
- https://github.com/ipxe/ipxe/pull/794
- https://github.com/ipxe/ipxe/discussions/679
- https://github.com/ipxe/ipxe/discussions/544

**Comment by stappersg** [comment]
Duplicate of #886. My advice is to leave this one open until an increase of the version number has happened, as an attempt to prevent further duplicates

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/ipxe/ipxe/discussions/679

**Comment by Neustradamus** [comment]
Good news, a new version has been released 3 years after my initial request: 2.0.0 (2026-03-06):
- https://github.com/ipxe/ipxe/releases/tag/v2.0.0
