### ISSUE TITLE
Problem when using ipxe after kexec

### ISSUE THREAD

**Issue by DenisVASI9** [ipxe/ipxe#916]
I loaded ipxe via grub4dos using kexec.
But ipxe reported that my network card (mellanox connect x3) is disabled by bios. Can I turn it on with ipxe ?
Is there any way i can initialize it ?

**Comment by NiKiZe** [comment]
Could you give more details on which binary you are using (build target) and the exact error message you are seeing? (All iPXE errors has a message and link to iPXE.org for more info)

**Comment by DenisVASI9** [comment]
@NiKiZe 
I build ipxe using
```bash
cd ipxe/src && make -j8
```

and booting using:

```bash
kexec --load /grub.exe \
    --initrd=/ipxe.iso \
    --command-line="--config-file=debug on; map --mem (rd)+1 (0xff); map --hook; root (0xff); kernel /ipxe.lkrn; boot"
kexec --exec
```

**Comment by DenisVASI9** [comment]
![Screenshot_2023-03-09_15-48-22](https://user-images.githubusercontent.com/48092110/224002341-1d6026d6-6cf5-49ee-9b71-2b2c2f30b69c.png)

**Comment by NiKiZe** [comment]
So you are running ipxe.lkrn from ipxe.iso?
And you have also grub.exe in the mix?

The debug output does not match the build command.

Any chance that you can use iPXE.lkrn directly, without debug, just so we get a starting point of the issue?
And then press ctrl+b to get shell and run ifstat.

**Comment by DenisVASI9** [comment]
Sorry, I forgot to mention that I used debug.
```bash
make bin/ipxe.iso DEBUG=pci -j6
```
ipxe works fine on my computer if I don't use it with kexec, but I need to run it from kexec, so I use grub4dos

**Comment by DenisVASI9** [comment]
@NiKiZe I can follow any instructions you ask, thanks for your help

**Comment by DenisVASI9** [comment]
After kexec my keyboard does not work, so I can only compile ipxe with the ifstat script inside

**Comment by DenisVASI9** [comment]
![Screenshot_2023-03-09_16-51-16](https://user-images.githubusercontent.com/48092110/224014957-246f1ed2-b280-48cb-975b-b9f989f1c0cc.png)

**Comment by NiKiZe** [comment]
Where you able to run iPXE kernel without the grub and iso middleware? (Do you have steps to reproduce?)
Use embedded script with ifstat and grab the output.. no debug.

And in this stage, specify what the problem is. And not base your error description on the output of debug message.

Example: "when I kexec into ipxe.lkrn on my machine it refuses to identify and open my NIC with pciid xxxx:yyyy"

Are you booting this system originally in PCBIOS mode?
Your way of using iPXE here is not really the intended way, and ipxe is not a full Linux kernel, it does require a working PCBIOS environment to run.

I think your best bet is to deal with the pci bus from within Linux before kexec. (But not really sure that is even an issue)

I'm willing to try and understand what is going on a little bit more. But please be prepared for a possible "kexec not supported" outcome. Have you been using this technique on any other machines?

**Comment by DenisVASI9** [comment]
Oh, sorry, but I am not sure if I can run ipxe without iso and grub using kexec. 
Or do you want me to just boot it from a flash drive without kexec?

**Comment by DenisVASI9** [comment]
And yes, I work in pcbios

**Comment by mcb30** [comment]
It looks as though you are getting all zeroes returned from any register that iPXE reads on that card.

Please test first without involving kexec or GRUB in any way, to see if this is a problem with the actual device, or a quirk of the way that you are invoking iPXE.

**Comment by DenisVASI9** [comment]
@mcb30 When I boot ipxe from a flash drive using grub - mellanox works fine

**Comment by mcb30** [comment]
> @mcb30 When I boot ipxe from a flash drive using grub - mellanox works fine

OK.  Is that going through the same combination of grub4dos and `ipxe.iso` as in your failure case, or with some other flash drive + grub setup?

**Comment by DenisVASI9** [comment]
It's a grub-install and ipxe.lkrn 

```bash
make bin/ixpe.lkrn -j8 DEBUG=pci,hermon
```

**Comment by DenisVASI9** [comment]
I use grub4dos with kexec because I cannot execute 
```bash
kexec -l ipxe.lkrn
```
The computer just goes into bios, as if ignoring ipxe

**Comment by mcb30** [comment]
> It's a grub-install and ipxe.lkrn
> 
> ```shell
> make bin/ipxe.lkrn -j8 DEBUG=pci,hermon
> ```

OK.  Then this test is too dissimilar to your failure case.  You cannot tell from your results if the problem is related to kexec or to grub4dos.

You need to get your success case as close as possible to your failure case, so that you can narrow down the problem.

**Comment by DenisVASI9** [comment]
Okay, I will create a flash drive with grub4dos and iso

**Comment by DenisVASI9** [comment]
I created a flash drive with grub4dos and ipxe.iso.
I attach the commands:
```bash
sudo dd if=/dev/zero of=/dev/sdc status=progress
sudo ./bootlace.com /dev/sdc
sudo mkfs.vfat /dev/sdc1
sudo mount /dev/sdc1 /mnt
sudo cp -r grub4dos-0.4.4/* /mnt
cd ipxe/src
make -j5 DEBUG=pci,hermon
sudo cp bin/ipxe.iso /mnt

sudo nano /mnt/menu.lst:
title ipxe
map /ISO/ipxe.iso (0xff) || map --mem /ISO/ipxe.iso (0xff)
map --hook
root (0xff)
chainloader (0xff)
```

And it works fine

**Comment by DenisVASI9** [comment]
@mcb30 Hi!
I booted into archiso and ran the following commands:
```bash
echo 0000:03:00.0 | sudo tee /sys/bus/pci/devices/0000:03:00.0/driver/unbind
sleep 5
rmmod mlx4_ib
rmmod mlx4_en
rmmod mlx4_core
kexec --load /root/grub4dos-0.4.4/grub.exe \
    --initrd=/root/ipxe.iso \
    --command-line="--config-file=debug on; map --mem (rd)+1 (0xff); map --hook; root (0xff); kernel /ipxe.lkrn; boot"
systemctl kexec
```
I got this condition:

**Comment by DenisVASI9** [comment]
Ok. The output from ipxe was no different, it showed zeros everywhere again

**Comment by mcb30** [comment]
> @mcb30 Hi! I booted into archiso and ran the following commands:
> 
> ```shell
> echo 0000:03:00.0 | sudo tee /sys/bus/pci/devices/0000:03:00.0/driver/unbind
> sleep 5
> rmmod mlx4_ib
> rmmod mlx4_en
> rmmod mlx4_core
> kexec --load /root/grub4dos-0.4.4/grub.exe \
>     --initrd=/root/ipxe.iso \
>     --command-line="--config-file=debug on; map --mem (rd)+1 (0xff); map --hook; root (0xff); kernel /ipxe.lkrn; boot"
> systemctl kexec
> ```

This conflates two of the tests that I asked you to try, and completely omits the third test.

Please try all three tests separately.

**Comment by DenisVASI9** [comment]
Okay, I'll do it

**Comment by DenisVASI9** [comment]
I did the first two tests, the result is the same. 
I did not use systemd kexec so that systemd would not interfere with the experiment

test 1:
```bash
echo 0000:03:00.0 | sudo tee /sys/bus/pci/devices/0000:03:00.0/driver/unbind
sleep 5
kexec --load /root/grub4dos-0.4.4/grub.exe \
    --initrd=/root/ipxe.iso \
    --command-line="--config-file=debug on; map --mem (rd)+1 (0xff); map --hook; root (0xff); kernel /ipxe.lkrn; boot"
kexec -e
```

test 2:
```bash
rmmod mlx4_ib
rmmod mlx4_en
rmmod mlx4_core

kexec --load /root/grub4dos-0.4.4/grub.exe \
    --initrd=/root/ipxe.iso \
    --command-line="--config-file=debug on; map --mem (rd)+1 (0xff); map --hook; root (0xff); kernel /ipxe.lkrn; boot"
kexec -e
```

**Comment by DenisVASI9** [comment]
I will build a kernel without mlx4 modules to make an experiment, if you don't mind

**Comment by DenisVASI9** [comment]
@mcb30 
I created a kernel and initrd that had no network drivers at all and loaded it from a flash drive. 
```bash
kernel /boot/vmlinuz
initrd /boot/initrd.cpio
```

After kexec ipxe also considers that there are only zeros.

**Comment by DenisVASI9** [comment]
I would like to point out that ipxe sees my network card on the motherboard, but I would still like to use mellanox, I have no way to run copper cables

**Comment by DenisVASI9** [comment]
@mcb30 
I tried calling more reset and other sys files for the driver, the behavior is the same

**Comment by mcb30** [comment]
Best guess at this point is that it's something related to the PCI power management state that the device gets left in when a `kexec` happens.  iPXE doesn't get involved in power management, so if the kernel leaves the device in some kind of power-down state that isn't reset by the reset mechanism in `hermon_reset()`, then the device will not be functional in iPXE.

You could also try adding a large delay in `hermon_reset()` immediately after the `writel ( HERMON_RESET_MAGIC, ... )`, just in case the write is somehow ending up getting posted behind the first read from `PCI_VENDOR_ID` within the loop.

**Comment by DenisVASI9** [comment]
Hi. I added mDelay(10000)
And increased the HERMON_RESET_MAX_WAIT_MS constant to 10000. 
It didn't change the result. 
I also built a linux kernel without pci, usb or network support.
This also didn't change the result.
When I did one of the experiments, separate from the above described, I accidentally managed to get the following status:
I loaded ipxe and did sanhook, after that I http loaded the kernel without pci support into memory and after rebooting into grub4dos and then calling a second ipxe it was able to initialize the card, although there was a doorbell excus error, it did not affect the performance. 
Did this give you any ideas?

**Comment by mcb30** [comment]
It's great that you have found some way in which iPXE works with the card after a `kexec`. However, there are quite a lot of random changes in that one test.  To get anywhere near a root cause diagnosis, you'll need to be much more controlled about your testing, and gradually narrow down the difference between the "working" and "not working" test scenarios.

**Comment by DenisVASI9** [comment]
@mcb30 
I ran all these tests separately. 
I can't say that the solution I found is satisfactory, rather I found it by accident. 
Can you help me further?
I'm ready to fulfill all your requests or even give you access to the hardware via ipmi

**Comment by mcb30** [comment]
> @mcb30 I ran all these tests separately.

"loaded ipxe and did sanhook, after that I http loaded the kernel without pci support into memory and after rebooting into grub4dos and then calling a second ipxe" is a lot of changes from your base scenario! :slightly_smiling_face: 

Please just try to systematically narrow down the difference between your "known working" and "known not working" test cases.

> Can you help me further? I'm ready to fulfill all your requests or even give you access to the hardware via ipmi

I don't have the time to debug this myself, sorry.  It's an obscure use case that I don't personally need, so I'm happy to give you the pointers I've already given you, but you will need to do the debug work yourself.

**Comment by belaaaaar** [comment]
That's interesting to me, too.
I repeated the experiments of DenisVASI9
I did a boot via ipxe and got the debug message hermon
"Hermon 0x285f4 firmware area at physical [b99eb000, b9ff1000]" 
After that I did a kexec in grub4dos with ipxe.iso 
"Hermon 0xe8714 firmware area at physical [b9ff1000, b9ff1000]" 
I then added the log to the "hermon_reset" function: 

DBGC ( hermon, "Hermon reset address \n", ( hermon->config + HERMON_RESET_OFFSET));
and did the same two tests: 

1-grub4dos->ipxe
"Hermon reset address 3D49A010
Hermon 0x285f4 firmware area at physical [b9ff1000, b9ff1000]" 
2- kexec->grub4dos->ipxe
"Hermon reset address 3D56F010
Hermon 0xe8714 firmware area at physical [b9ff1000, b9ff1000]" 

It all looks like some kind of incomprehensible offset...
