### ISSUE TITLE
Error on compile EFI(arm64) with params CPUID_SETTINGS

### ISSUE THREAD

**Issue by weijiangxin315** [ipxe/ipxe#926]
#make EMBED=default.ipxe  bin-arm64-efi/ipxe.efi
  [DEPS] config/config.c
  [BUILD] bin-arm64-efi/config.o
  [AR] bin-arm64-efi/blib.a
ar: creating bin-arm64-efi/blib.a
  [VERSION] bin-arm64-efi/version.ipxe.efi.o
  [LD] bin-arm64-efi/ipxe.efi.tmp
ld: bin-arm64-efi/blib.a(config.o): in function `__requiring_symbol__':
config.c:(.tbl.requiring_symbols+0x0): undefined reference to `obj_cpuid_settings'
make: *** [Makefile.housekeeping:1222: bin-arm64-efi/ipxe.efi.tmp] Error 1
rm bin-arm64-efi/version.ipxe.efi.o

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-linux-gnu/7.3.0/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,fortran,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/home/abuild/rpmbuild/BUILD/gcc-7.3.0/obj-aarch64-linux-gnu/isl-install --without-cloog --enable-gnu-indirect-function --build=aarch64-linux-gnu --with-stage1-ldflags=' -Wl,-z,relro,-z,now' --with-boot-ldflags=' -Wl,-z,relro,-z,now' --with-multilib-list=lp64
Thread model: posix
gcc version 7.3.0 (GCC)

**Comment by mcb30** [comment]
`cpuid` is an x86-specific mechanism and does not exist on ARM.
