### ISSUE TITLE
Files to "make bin-x86_64-efi/ipxe.efi" are missing

### ISSUE THREAD

**Issue by Jcpetrucci** [ipxe/ipxe#927]
Trying to follow the instructions from https://ipxe.org/download that say

`make bin-x86_64-efi/ipxe.efi`

but there is no ipxe.efi and there is no directory bin-x86_64-efi
```
$ git remote -v
origin  https://github.com/ipxe/ipxe.git (fetch)
origin  https://github.com/ipxe/ipxe.git (push)
*$ find . -type f -name '*.efi'
./src/arch/x86/Makefile.efi
./src/arch/i386/Makefile.efi
./src/arch/arm32/Makefile.efi
./src/arch/arm64/Makefile.efi
./src/arch/arm/Makefile.efi
./src/arch/x86_64/Makefile.efi
./src/Makefile.efi
$ find . -type d -name 'bin-x86_64-efi'
$ 
```

**Comment by mcb30** [comment]
Nothing is wrong here.  The directory `bin-x86_64-efi` will be created when you try running the command `make bin-x86_64-efi/ipxe.efi` as per the instructions.
