### ISSUE TITLE
no user-class in DHCPv6 request

### ISSUE THREAD

**Issue by 4xoc** [ipxe/ipxe#951]
In DHCPv6 requests no user-class option is sent by iPXE. There's code that should add the option but tcpdumping requests shows no such option. This happens when building from source and using the precompiled EFI binary. Setting the user class in CLI doesn't work as well.

**Comment by mcb30** [comment]
Seems to work as expected:

![Screenshot_20230621_133609](https://github.com/ipxe/ipxe/assets/692245/20c51be0-7182-481a-b447-ce4f090496ca)
