### ISSUE TITLE
Add support for efi variables

### ISSUE THREAD

**Issue by Cornelicorn** [ipxe/ipxe#966]
It would be nice to add support for reading and writing UEFI variables. This would allow to store settings or menu defaults between boots. My use case would be to encode which operating system is going to be installed in a controlled manner from the host itself without needing any operating system installed or any disk present. This could also be used on diskless clients.

**Comment by Hammarskjold** [comment]
Yeah, we have done some scaffolding on this. It's easy to read (using known GUIDs) but writing is harder as all settings has to be under a vendor GUID.

@mcb30 what about starting with read as we discusses last?

//Andreas
