### ISSUE TITLE
IPXE initialising devices.WARNING: Using legacy NIC wrapper on 79:79:79:79:79:79

### ISSUE THREAD

**Issue by scott-xu** [ipxe/ipxe#972]
Hi, I'm having issue to boot in UEFI mode with ipxe.efi.
It works in PCBIOS mode using undionly.kpxe.
It works in UEFI mode using snponly.ipxe

![rpviewer (7)](https://github.com/ipxe/ipxe/assets/1913505/3fa90c3c-acac-4f16-9668-11a2cd81235e)
![rpviewer (8)](https://github.com/ipxe/ipxe/assets/1913505/14a7d7a7-3ff0-4f73-a0f9-c512b1cd2d9f)
![image](https://github.com/ipxe/ipxe/assets/1913505/57b9ef2d-835a-4dfc-8ffa-d46581de82fb)

**Comment by NiKiZe** [comment]
The legacy NIC wrapper warning is a warning, not an error.
Probably a virtual management nic.

You are not clear on where you expect to boot from, but I guess one of the broadcom ports. That is a known buggy driver, please use snponly or snp.efi

**Comment by scott-xu** [comment]
Hi @NiKiZe , yes I wan to boot from Broadcom NetXtreme Gigabit Ethernet

**Comment by scott-xu** [comment]
Is there anyway to fallback to snp protocol in ipxe.efi for special PCIID?

**Comment by NiKiZe** [comment]
> Is there anyway to fallback to snp protocol in ipxe.efi for special PCIID?

You can remove the driver, or the pciid definition line in the driver.

**Comment by scott-xu** [comment]
> > Is there anyway to fallback to snp protocol in ipxe.efi for special PCIID?
> 
> You can remove the driver, or the pciid definition line in the driver.

Thanks! That works.
