### ISSUE TITLE
iPXE cann't boot with connection timed out

### ISSUE THREAD

**Issue by kuangrongjian** [ipxe/ipxe#998]
iPXE cann't boot with displaying connect time out error message when use 22 NIC device.

IPXE 1.21.1+(gc30b7) testing has issues, but iPXE 1.21.1+(gd3c89) has no issues，when use BCM957414N4140C. 
This issue is related to the number of network cards, and reducing the number of network cards IPXE 1.21.1+(gc30b7) is not a problem.

![image002(07-17-11-04-16)](https://github.com/ipxe/ipxe/assets/34646966/82eaee0a-1700-4f3f-a69f-77c12b1f9240)

**Comment by NiKiZe** [comment]
Search before posting new issues.
Make sure you post the error message (including url in the message), and that is after actually following that url and making sure that this is not a user error in any way.

Closing mainly as duplicate. But also due to lack of information.
Such as at least ifstat.
